//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

#if GENIES_SDK && !GENIES_INTERNAL
internal class AvatarController : global::System.IDisposable {
#else
public class AvatarController : global::System.IDisposable {
#endif
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AvatarController(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AvatarController obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AvatarController obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AvatarController() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnBehaviourWrapperPINVOKE.delete_AvatarController(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public AvatarController() : this(GnBehaviourWrapperPINVOKE.new_AvatarController(), true) {
  }

  public void SetPoseContext(PoseContext context) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetPoseContext(swigCPtr, PoseContext.getCPtr(context));
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Update(float deltaTime) {
    GnBehaviourWrapperPINVOKE.AvatarController_Update(swigCPtr, deltaTime);
  }

  public void SetIdle(AnimationClip clip) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetIdle(swigCPtr, AnimationClip.getCPtr(clip));
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void PlayBoredom(AnimationClip clip, float blendInTime, float blendOutTime) {
    GnBehaviourWrapperPINVOKE.AvatarController_PlayBoredom(swigCPtr, AnimationClip.getCPtr(clip), blendInTime, blendOutTime);
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void PlayGesture(AnimationClip clip, global::System.IntPtr onComplete, float blendInTime, float blendOutTime, float holdTime) {
    GnBehaviourWrapperPINVOKE.AvatarController_PlayGesture__SWIG_0(swigCPtr, AnimationClip.getCPtr(clip), onComplete, blendInTime, blendOutTime, holdTime);
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void PlayGesture(AnimationClip clip, global::System.IntPtr onComplete, float blendInTime, float blendOutTime) {
    GnBehaviourWrapperPINVOKE.AvatarController_PlayGesture__SWIG_1(swigCPtr, AnimationClip.getCPtr(clip), onComplete, blendInTime, blendOutTime);
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void PlayEmotionBody(AnimationClip clip, global::System.IntPtr onComplete, float blendInTime, float blendOutTime) {
    GnBehaviourWrapperPINVOKE.AvatarController_PlayEmotionBody(swigCPtr, AnimationClip.getCPtr(clip), onComplete, blendInTime, blendOutTime);
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetEmotion(AnimationClip clipMin, AnimationClip clipMax) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetEmotion(swigCPtr, AnimationClip.getCPtr(clipMin), AnimationClip.getCPtr(clipMax));
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetEmotionWeight(float weight, float intensity) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetEmotionWeight(swigCPtr, weight, intensity);
  }

  public void SetTalking(AnimationClip clip) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetTalking(swigCPtr, AnimationClip.getCPtr(clip));
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTalkingWeight(float weight) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetTalkingWeight(swigCPtr, weight);
  }

  public void SetBreath(AnimationClip clip) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetBreath(swigCPtr, AnimationClip.getCPtr(clip));
    if (GnBehaviourWrapperPINVOKE.SWIGPendingException.Pending) throw GnBehaviourWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetBreathWeight(float weight, float speedMultiplier) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetBreathWeight__SWIG_0(swigCPtr, weight, speedMultiplier);
  }

  public void SetBreathWeight(float weight) {
    GnBehaviourWrapperPINVOKE.AvatarController_SetBreathWeight__SWIG_1(swigCPtr, weight);
  }

  public float GetIdleWeight() {
    float ret = GnBehaviourWrapperPINVOKE.AvatarController_GetIdleWeight(swigCPtr);
    return ret;
  }

  public float GetBoredomWeight() {
    float ret = GnBehaviourWrapperPINVOKE.AvatarController_GetBoredomWeight(swigCPtr);
    return ret;
  }

  public float GetGestureWeight() {
    float ret = GnBehaviourWrapperPINVOKE.AvatarController_GetGestureWeight(swigCPtr);
    return ret;
  }

  public PoseContext GetPoseContext() {
    PoseContext ret = new PoseContext(GnBehaviourWrapperPINVOKE.AvatarController_GetPoseContext(swigCPtr), true);
    return ret;
  }

  public Pose GetPose() {
    Pose ret = new Pose(GnBehaviourWrapperPINVOKE.AvatarController_GetPose(swigCPtr), true);
    return ret;
  }

  public PoseMask GetDirtyMask() {
    PoseMask ret = new PoseMask(GnBehaviourWrapperPINVOKE.AvatarController_GetDirtyMask(swigCPtr), true);
    return ret;
  }

}

}
