//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

#if GENIES_SDK && !GENIES_INTERNAL
internal class ContainerApi : global::System.IDisposable {
#else
public class ContainerApi : global::System.IDisposable {
#endif
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ContainerApi(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ContainerApi obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ContainerApi obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ContainerApi() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnContainerWrapperPINVOKE.delete_ContainerApi(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ContainerApi(string resolverConfigJson) : this(GnContainerWrapperPINVOKE.new_ContainerApi(resolverConfigJson), true) {
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public Entity LoadCombinableAsset(string uri, UnorderedMapString params_) {
    Entity ret = new Entity(GnContainerWrapperPINVOKE.ContainerApi_LoadCombinableAsset(swigCPtr, uri, UnorderedMapString.getCPtr(params_)), true);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LoadCombinableAssetAsync(string uri, UnorderedMapString params_) {
    int ret = GnContainerWrapperPINVOKE.ContainerApi_LoadCombinableAssetAsync(swigCPtr, uri, UnorderedMapString.getCPtr(params_));
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsAsyncLoadComplete(int handle) {
    bool ret = GnContainerWrapperPINVOKE.ContainerApi_IsAsyncLoadComplete(swigCPtr, handle);
    return ret;
  }

  public Entity GetAsyncLoadResult(int handle) {
    Entity ret = new Entity(GnContainerWrapperPINVOKE.ContainerApi_GetAsyncLoadResult(swigCPtr, handle), true);
    return ret;
  }

  public Texture LoadTexture(string uri, UnorderedMapString params_) {
    Texture ret = new Texture(GnContainerWrapperPINVOKE.ContainerApi_LoadTexture(swigCPtr, uri, UnorderedMapString.getCPtr(params_)), true);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LoadTextureAsync(string uri, UnorderedMapString params_) {
    int ret = GnContainerWrapperPINVOKE.ContainerApi_LoadTextureAsync(swigCPtr, uri, UnorderedMapString.getCPtr(params_));
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsTextureAsyncLoadComplete(int handle) {
    bool ret = GnContainerWrapperPINVOKE.ContainerApi_IsTextureAsyncLoadComplete(swigCPtr, handle);
    return ret;
  }

  public Texture GetTextureAsyncLoadResult(int handle) {
    Texture ret = new Texture(GnContainerWrapperPINVOKE.ContainerApi_GetTextureAsyncLoadResult(swigCPtr, handle), true);
    return ret;
  }

  public Texture LoadIcon(string uri, UnorderedMapString params_) {
    Texture ret = new Texture(GnContainerWrapperPINVOKE.ContainerApi_LoadIcon(swigCPtr, uri, UnorderedMapString.getCPtr(params_)), true);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LoadIconAsync(string uri, UnorderedMapString params_) {
    int ret = GnContainerWrapperPINVOKE.ContainerApi_LoadIconAsync(swigCPtr, uri, UnorderedMapString.getCPtr(params_));
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsIconAsyncLoadComplete(int handle) {
    bool ret = GnContainerWrapperPINVOKE.ContainerApi_IsIconAsyncLoadComplete(swigCPtr, handle);
    return ret;
  }

  public Texture GetIconAsyncLoadResult(int handle) {
    Texture ret = new Texture(GnContainerWrapperPINVOKE.ContainerApi_GetIconAsyncLoadResult(swigCPtr, handle), true);
    return ret;
  }

  public bool CancelAsyncLoad(int handle) {
    bool ret = GnContainerWrapperPINVOKE.ContainerApi_CancelAsyncLoad(swigCPtr, handle);
    return ret;
  }

  public void CancelAllAsyncLoads() {
    GnContainerWrapperPINVOKE.ContainerApi_CancelAllAsyncLoads(swigCPtr);
  }

  public bool CancelTextureAsyncLoad(int handle) {
    bool ret = GnContainerWrapperPINVOKE.ContainerApi_CancelTextureAsyncLoad(swigCPtr, handle);
    return ret;
  }

  public void CancelAllTextureAsyncLoads() {
    GnContainerWrapperPINVOKE.ContainerApi_CancelAllTextureAsyncLoads(swigCPtr);
  }

  public bool CancelIconAsyncLoad(int handle) {
    bool ret = GnContainerWrapperPINVOKE.ContainerApi_CancelIconAsyncLoad(swigCPtr, handle);
    return ret;
  }

  public void CancelAllIconAsyncLoads() {
    GnContainerWrapperPINVOKE.ContainerApi_CancelAllIconAsyncLoads(swigCPtr);
  }

  public TextureSettings TextureSettings() {
    global::System.IntPtr cPtr = GnContainerWrapperPINVOKE.ContainerApi_TextureSettings(swigCPtr);
    TextureSettings ret = (cPtr == global::System.IntPtr.Zero) ? null : new TextureSettings(cPtr, false);
    return ret;
  }

  public void DestroyTextureSettings() {
    GnContainerWrapperPINVOKE.ContainerApi_DestroyTextureSettings(swigCPtr);
  }

}

}
