using AOT;
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

class GnContainerWrapperPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="SWIGRegisterExceptionCallbacks_GnContainerWrapper")]
    public static extern void SWIGRegisterExceptionCallbacks_GnContainerWrapper(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="SWIGRegisterExceptionArgumentCallbacks_GnContainerWrapper")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_GnContainerWrapper(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    [AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))]
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_GnContainerWrapper(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_GnContainerWrapper(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="SWIGRegisterStringCallback_GnContainerWrapper")]
    public static extern void SWIGRegisterStringCallback_GnContainerWrapper(SWIGStringDelegate stringDelegate);

    [AOT.MonoPInvokeCallback(typeof(SWIGStringDelegate))]
    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_GnContainerWrapper(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static GnContainerWrapperPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_new_UnorderedMapString__SWIG_0")]
  public static extern global::System.IntPtr new_UnorderedMapString__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_new_UnorderedMapString__SWIG_1")]
  public static extern global::System.IntPtr new_UnorderedMapString__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_size")]
  public static extern uint UnorderedMapString_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_empty")]
  public static extern bool UnorderedMapString_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_Clear")]
  public static extern void UnorderedMapString_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_getitem")]
  public static extern string UnorderedMapString_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_setitem")]
  public static extern void UnorderedMapString_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_ContainsKey")]
  public static extern bool UnorderedMapString_ContainsKey(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_Add")]
  public static extern void UnorderedMapString_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_Remove")]
  public static extern bool UnorderedMapString_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_create_iterator_begin")]
  public static extern global::System.IntPtr UnorderedMapString_create_iterator_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_get_next_key")]
  public static extern string UnorderedMapString_get_next_key(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_UnorderedMapString_destroy_iterator")]
  public static extern void UnorderedMapString_destroy_iterator(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_delete_UnorderedMapString")]
  public static extern void delete_UnorderedMapString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_CParam_key_set")]
  public static extern void CParam_key_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_CParam_key_get")]
  public static extern string CParam_key_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_CParam_value_set")]
  public static extern void CParam_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_CParam_value_get")]
  public static extern string CParam_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_new_CParam")]
  public static extern global::System.IntPtr new_CParam();

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_delete_CParam")]
  public static extern void delete_CParam(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_new_ContainerApi")]
  public static extern global::System.IntPtr new_ContainerApi(string jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_delete_ContainerApi")]
  public static extern void delete_ContainerApi(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_LoadCombinableAsset")]
  public static extern global::System.IntPtr ContainerApi_LoadCombinableAsset(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_LoadCombinableAssetAsync")]
  public static extern int ContainerApi_LoadCombinableAssetAsync(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_IsAsyncLoadComplete")]
  public static extern bool ContainerApi_IsAsyncLoadComplete(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_GetAsyncLoadResult")]
  public static extern global::System.IntPtr ContainerApi_GetAsyncLoadResult(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_LoadTexture")]
  public static extern global::System.IntPtr ContainerApi_LoadTexture(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_LoadTextureAsync")]
  public static extern int ContainerApi_LoadTextureAsync(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_IsTextureAsyncLoadComplete")]
  public static extern bool ContainerApi_IsTextureAsyncLoadComplete(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_GetTextureAsyncLoadResult")]
  public static extern global::System.IntPtr ContainerApi_GetTextureAsyncLoadResult(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_LoadIcon")]
  public static extern global::System.IntPtr ContainerApi_LoadIcon(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_LoadIconAsync")]
  public static extern int ContainerApi_LoadIconAsync(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_IsIconAsyncLoadComplete")]
  public static extern bool ContainerApi_IsIconAsyncLoadComplete(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_GetIconAsyncLoadResult")]
  public static extern global::System.IntPtr ContainerApi_GetIconAsyncLoadResult(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_CancelAsyncLoad")]
  public static extern bool ContainerApi_CancelAsyncLoad(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_CancelAllAsyncLoads")]
  public static extern void ContainerApi_CancelAllAsyncLoads(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_CancelTextureAsyncLoad")]
  public static extern bool ContainerApi_CancelTextureAsyncLoad(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_CancelAllTextureAsyncLoads")]
  public static extern void ContainerApi_CancelAllTextureAsyncLoads(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_CancelIconAsyncLoad")]
  public static extern bool ContainerApi_CancelIconAsyncLoad(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_CancelAllIconAsyncLoads")]
  public static extern void ContainerApi_CancelAllIconAsyncLoads(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_TextureSettings")]
  public static extern global::System.IntPtr ContainerApi_TextureSettings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(Genies.NafPlugin.ImportName.Value, EntryPoint="CSharp_GnWrappers_ContainerApi_DestroyTextureSettings")]
  public static extern void ContainerApi_DestroyTextureSettings(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
