//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

#if GENIES_SDK && !GENIES_INTERNAL
internal enum StandardVertexAttribute {
#else
public enum StandardVertexAttribute {
#endif
  Position = 0,
  Normal = 1,
  Tangent = 2,
  TexCoord = 3,
  Color = 4,
  Joints = 5,
  Weights = 6
}

}
