//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

#if GENIES_SDK && !GENIES_INTERNAL
internal enum TranscodableTextureFormat : byte {
#else
public enum TranscodableTextureFormat : byte {
#endif
  Undefined = 0,
  UASTC = 1,
  ETC1S = 2,
  PNG = 3
}

}
