#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.87
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Represents a smart avatar with AI capabilities
    /// </summary>
    [DataContract]
        public partial class SmartAvatar :  IEquatable<SmartAvatar>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SmartAvatar" /> class.
        /// </summary>
        /// <param name="avatarId">ID of the avatar template.</param>
        /// <param name="brainId">ID of the AI brain configuration.</param>
        /// <param name="behaviorId">ID of the behavior configuration.</param>
        /// <param name="workspaceId">ID of the workspace this smart avatar belongs to.</param>
        /// <param name="description">Optional description of the smart avatar.</param>
        public SmartAvatar(string avatarId = default(string), string brainId = default(string), string behaviorId = default(string), string workspaceId = default(string), string description = default(string))
        {
            this.AvatarId = avatarId;
            this.BrainId = brainId;
            this.BehaviorId = behaviorId;
            this.WorkspaceId = workspaceId;
            this.Description = description;
        }
        
        /// <summary>
        /// Unique identifier of the smart avatar
        /// </summary>
        /// <value>Unique identifier of the smart avatar</value>
        [DataMember(Name="smart_avatar_id", EmitDefaultValue=false)]
        public string SmartAvatarId { get; private set; }

        /// <summary>
        /// ID of the avatar template
        /// </summary>
        /// <value>ID of the avatar template</value>
        [DataMember(Name="avatar_id", EmitDefaultValue=false)]
        public string AvatarId { get; set; }

        /// <summary>
        /// ID of the AI brain configuration
        /// </summary>
        /// <value>ID of the AI brain configuration</value>
        [DataMember(Name="brain_id", EmitDefaultValue=false)]
        public string BrainId { get; set; }

        /// <summary>
        /// ID of the behavior configuration
        /// </summary>
        /// <value>ID of the behavior configuration</value>
        [DataMember(Name="behavior_id", EmitDefaultValue=false)]
        public string BehaviorId { get; set; }

        /// <summary>
        /// ID of the workspace this smart avatar belongs to
        /// </summary>
        /// <value>ID of the workspace this smart avatar belongs to</value>
        [DataMember(Name="workspace_id", EmitDefaultValue=false)]
        public string WorkspaceId { get; set; }

        /// <summary>
        /// ID of the user who created this smart avatar
        /// </summary>
        /// <value>ID of the user who created this smart avatar</value>
        [DataMember(Name="user_id", EmitDefaultValue=false)]
        public string UserId { get; private set; }

        /// <summary>
        /// Unix timestamp when the smart avatar was created
        /// </summary>
        /// <value>Unix timestamp when the smart avatar was created</value>
        [DataMember(Name="created_at", EmitDefaultValue=false)]
        public long? CreatedAt { get; private set; }

        /// <summary>
        /// Optional description of the smart avatar
        /// </summary>
        /// <value>Optional description of the smart avatar</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SmartAvatar {\n");
            sb.Append("  SmartAvatarId: ").Append(SmartAvatarId).Append("\n");
            sb.Append("  AvatarId: ").Append(AvatarId).Append("\n");
            sb.Append("  BrainId: ").Append(BrainId).Append("\n");
            sb.Append("  BehaviorId: ").Append(BehaviorId).Append("\n");
            sb.Append("  WorkspaceId: ").Append(WorkspaceId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SmartAvatar);
        }

        /// <summary>
        /// Returns true if SmartAvatar instances are equal
        /// </summary>
        /// <param name="input">Instance of SmartAvatar to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SmartAvatar input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SmartAvatarId == input.SmartAvatarId ||
                    (this.SmartAvatarId != null &&
                    this.SmartAvatarId.Equals(input.SmartAvatarId))
                ) && 
                (
                    this.AvatarId == input.AvatarId ||
                    (this.AvatarId != null &&
                    this.AvatarId.Equals(input.AvatarId))
                ) && 
                (
                    this.BrainId == input.BrainId ||
                    (this.BrainId != null &&
                    this.BrainId.Equals(input.BrainId))
                ) && 
                (
                    this.BehaviorId == input.BehaviorId ||
                    (this.BehaviorId != null &&
                    this.BehaviorId.Equals(input.BehaviorId))
                ) && 
                (
                    this.WorkspaceId == input.WorkspaceId ||
                    (this.WorkspaceId != null &&
                    this.WorkspaceId.Equals(input.WorkspaceId))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SmartAvatarId != null)
                    hashCode = hashCode * 59 + this.SmartAvatarId.GetHashCode();
                if (this.AvatarId != null)
                    hashCode = hashCode * 59 + this.AvatarId.GetHashCode();
                if (this.BrainId != null)
                    hashCode = hashCode * 59 + this.BrainId.GetHashCode();
                if (this.BehaviorId != null)
                    hashCode = hashCode * 59 + this.BehaviorId.GetHashCode();
                if (this.WorkspaceId != null)
                    hashCode = hashCode * 59 + this.WorkspaceId.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }
    }
}
