#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.4.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// UploadCompleteRequest
    /// </summary>
    [DataContract]
        public partial class UploadCompleteRequest :  IEquatable<UploadCompleteRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadCompleteRequest" /> class.
        /// </summary>
        /// <param name="totalUploadCount">totalUploadCount (required).</param>
        public UploadCompleteRequest(int? totalUploadCount = default(int?))
        {
            // to ensure "totalUploadCount" is required (not null)
            if (totalUploadCount == null)
            {
                throw new InvalidDataException("totalUploadCount is a required property for UploadCompleteRequest and cannot be null");
            }
            else
            {
                this.TotalUploadCount = totalUploadCount;
            }
        }
        
        /// <summary>
        /// Gets or Sets TotalUploadCount
        /// </summary>
        [DataMember(Name="total_upload_count", EmitDefaultValue=false)]
        public int? TotalUploadCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UploadCompleteRequest {\n");
            sb.Append("  TotalUploadCount: ").Append(TotalUploadCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UploadCompleteRequest);
        }

        /// <summary>
        /// Returns true if UploadCompleteRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UploadCompleteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UploadCompleteRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TotalUploadCount == input.TotalUploadCount ||
                    (this.TotalUploadCount != null &&
                    this.TotalUploadCount.Equals(input.TotalUploadCount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TotalUploadCount != null)
                    hashCode = hashCode * 59 + this.TotalUploadCount.GetHashCode();
                return hashCode;
            }
        }
    }
}
